version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: vite-app-prod
    ports:
      - "80:80"
    networks:
      - vite-prod-network

networks:
  vite-prod-network:
    driver: bridge